dist: trusty
sudo: false
git:
  depth: false
addons:
  sonarcloud:
    organization: "zommiommy-github"
    token:
      secure: XkXS1b7mavp2koS/IvO2ORpYjh9N4gZ4cTb2iGLdJk9lBtJmaF3Ytcodl/8RTTX7DR+qhU5J/KNeGByxQIsaqeOFQDLUkIpZR56Xxifa/6LC8Xq24Pgp1VM5x8bSknHNKMbYs1Z9MPzONxfPDE11I9XDdFH+ddnK5E0Cqi4syZg0CFNwCFWdAPKRLc2aImzabNBHz75EdBHnr3XAhc7VjkKaO7MqLe68sqQDEBuQNc63CebpEX0RzEtTMTxLBvG3vQutgJw6OI+qMg7vofKte9LZA9lFM6POUFHdGpSZLZkjkoTozVSXL+WKv5f1tDRuLMA6Qor2pTuwQZoEOGUKcLXYsXcXrLxy4hv3xT1HX8AMCtEDOz96tyeB+h1QlgKOQC+PEXdXN02BQnMPX1M+B2RnQEl3Zo5JdusiffWJ7NeuLUltA7RyHIU/9L92SMGzijmo5d/JQlx2zgb0FaotihfScGo/6BITtn/AhWDtOviAaN2OL62x9RS6qab16ekOs4a1VMfxAhvRxuLKxZXyjXjtBkfLhq35wNOdIe54uH3ReDi8Gc+AXlfPrLQitUx8tg8HcLv+QJVP36l8xeckpI7gQiX8tlZVBBszmQ8X9bLCSk5Xdp2DDtnTdKaXpUIl3Rkv5p4cSYu9vT5xmtxSmJRRAelXFnADwPv6ded9QzU=
language: python
python:
- '3.7'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=windows_generator --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml